jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2204:2022.10.2 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4

    steps:
        # Commands run in a Linux virtual machine environment
        - checkout
        - run: docker build . -t orianesav/cours-ci
        - run: docker run -d -p 8080:8080 orianesav/cours-ci
        - run: curl 127.0.0.1:8080
        - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - run: docker push orianesav/cours-ci:latest 